var CIRCLES_POPUP_CAPTION_BORDER = 2 ;
var CIRCLES_POPUP_CAPTION_HEIGHT = 14 ;
var CIRCLES_POPUP_SUB_CAPTION_HEIGHT = 14 ;
var CIRCLES_POPUP_MINIMIZE_WIDTH = 352 ;
var CIRCLES_POPUP_MINIMIZE_HEIGHT = CIRCLES_POPUP_CAPTION_HEIGHT + 4 ;

var CIRCLES_VIEWPORT_LEFT_MARGIN = 6 ;
var CIRCLES_VIEWPORT_RIGHT_MARGIN = 6 ;

var CIRCLES_VIEWPORT_ASPECT_RATIOS_SET = [ "5/4", "4/3", "16/10", "16/9" ] ;
var CIRCLES_VIEWPORT_ASPECT_RATIO = "" ;