var SYSTEM_ERROR_00 = "Unknown error." ;
var SYSTEM_ERROR_01 = "Time-out error." ;
var SYSTEM_ERROR_02 = "It's not possible to perform the chosen action." ;
var SYSTEM_ERROR_03 = "It's not possible to reach the server due to a lack of resources." ;
var SYSTEM_ERROR_04 = "Parameters are insufficient to perform the chosen action." ;
var SYSTEM_ERROR_06 = "Run-time error.\nTry to reload this page.\n\n(If this error persists, contact me)" ;
var SYSTEM_ERROR_07 = "Action has been successfully performed." ;
var SYSTEM_ERROR_08 = "Critical error: component(s) not available." ;
var SYSTEM_ERROR_404 = "HTTP 404 error.\nFile not found." ;